-- Create the Messages Table for the Inbox
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  direction TEXT CHECK (direction IN ('incoming', 'outgoing')),
  platform TEXT CHECK (platform IN ('whatsapp', 'email')),
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

-- Allow public read-write for MVP
CREATE POLICY "Allow public read-write on messages"
ON messages FOR ALL USING (true) WITH CHECK (true);

-- Insert a welcome message mock
INSERT INTO messages (lead_id, content, direction, platform, read)
SELECT id, 'Hi! I saw your proposal and would love to chat more about it.', 'incoming', 'whatsapp', false
FROM leads
LIMIT 1;
