-- Copy and paste this into your Supabase SQL Editor:

-- 1. Create the Leads Table
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  company TEXT,
  title TEXT,
  industry TEXT DEFAULT 'default',
  platform TEXT DEFAULT 'Email',
  method TEXT DEFAULT 'email',
  status TEXT DEFAULT 'Idle',
  context TEXT,
  icebreaker_draft TEXT,
  icebreaker_status TEXT DEFAULT 'pending',
  last_activity TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone with the anon key to read/write 
-- (Note: In a production app, you would restrict this to authenticated users only)
CREATE POLICY "Allow public read-write access"
ON leads
FOR ALL
USING (true)
WITH CHECK (true);
